test-django:
  image: python:3.9
  services:
    - postgres:14
  variables:
    POSTGRES_DB: library_ci_db
    POSTGRES_USER: library_ci_user
    POSTGRES_PASSWORD: postgres
    LIBRARY_DB_HOST: postgres
    LIBRARY_DB_NAME: library_ci_db
    LIBRARY_DB_USER: library_ci_user
    LIBRARY_DB_PASSWORD: postgres
    LIBRARY_ENVIRONMENT: ci
  script:
    - pip install -e .[test]
    - coverage run --source='.' manage.py test
    - coverage report
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'

test-react:
  image: node:14.18.1-alpine3.14
  script:
    - npm --prefix ui/ install
    - npm --prefix ui/ run test:ci
  coverage: '/All\sfiles.*?\s+(\d+.\d+)/'

include:
  - template: Security/SAST.gitlab-ci.yml
